function [BW,maskedImage] = segment_circle_Image(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 06-Oct-2018
%----------------------------------------------------


% Create empty mask.
BW = false(size(X,1),size(X,2));

% 범람 채우기
row = 183;
column = 254;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% disk을(를) 사용하여 마스크 닫기
radius = 7;
decomposition = 4;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

